#!/usr/bin/env python3
"""
Pattern extractor for prompt self-optimization.

Mines the observations and session summaries DB to extract:
1. Effective strategies (what worked in past sessions)
2. Common failure patterns (what to avoid)
3. Tool usage efficiency (which tools are most effective for which tasks)
4. Time-of-day patterns (when different work types succeed best)

Writes findings to ~/.claude-mem/patterns/patterns.md
which gets loaded into context for future sessions.
"""

import sqlite3
import os
import json
from datetime import datetime, timezone
from collections import defaultdict, Counter

DB_PATH = os.path.expanduser("~/.claude-mem/claude-mem.db")
MEMORY_DIR = os.path.expanduser("~/.claude-mem/patterns")
OUTPUT = os.path.join(MEMORY_DIR, "patterns.md")


def extract_tool_patterns(db):
    """Analyze which tools are used most effectively."""
    rows = db.execute("""
        SELECT type, title, facts
        FROM observations
        WHERE type IN ('bugfix', 'decision', 'feature')
        ORDER BY created_at_epoch DESC
        LIMIT 500
    """).fetchall()

    tool_counts = Counter()
    success_patterns = []

    for obs_type, title, facts_json in rows:
        title_lower = (title or "").lower()
        facts = []
        if facts_json:
            try:
                facts = json.loads(facts_json)
            except:
                pass

        # Extract tool mentions
        for fact in facts:
            fact_str = str(fact)
            if "Command:" in fact_str:
                cmd = fact_str.split("Command:")[1].strip()[:80]
                first_word = cmd.split()[0] if cmd else ""
                tool_counts[first_word] += 1

        # Track success patterns
        if obs_type in ("bugfix", "decision"):
            success_patterns.append({
                "type": obs_type,
                "title": title,
                "key_fact": facts[0] if facts else "",
            })

    return tool_counts, success_patterns


def extract_failure_patterns(db):
    """Find observations that mention errors or failures."""
    rows = db.execute("""
        SELECT title, facts, type
        FROM observations
        WHERE (title LIKE '%error%' OR title LIKE '%fail%' OR title LIKE '%fix%'
               OR facts LIKE '%error%' OR facts LIKE '%Error%')
        ORDER BY created_at_epoch DESC
        LIMIT 100
    """).fetchall()

    failures = []
    for title, facts_json, obs_type in rows:
        facts = []
        if facts_json:
            try:
                facts = json.loads(facts_json)
            except:
                pass

        error_facts = [f for f in facts if "error" in str(f).lower() or "Error" in str(f)]
        if error_facts:
            failures.append({
                "title": title,
                "error": error_facts[0][:200] if error_facts else "",
                "type": obs_type,
            })

    return failures


def extract_session_outcomes(db):
    """Analyze session summaries for what was accomplished."""
    rows = db.execute("""
        SELECT request, learned, completed, next_steps
        FROM session_summaries
        WHERE request IS NOT NULL AND request != ''
        ORDER BY created_at_epoch DESC
        LIMIT 30
    """).fetchall()

    outcomes = []
    for request, learned, completed, next_steps in rows:
        outcomes.append({
            "request": (request or "")[:100],
            "learned": (learned or "")[:150],
            "completed": (completed or "")[:150],
            "next_steps": (next_steps or "")[:150],
        })

    return outcomes


def extract_file_hotspots(db):
    """Find files that are modified most frequently."""
    rows = db.execute("""
        SELECT files_modified
        FROM observations
        WHERE files_modified IS NOT NULL AND files_modified != '[]'
        ORDER BY created_at_epoch DESC
        LIMIT 500
    """).fetchall()

    file_counts = Counter()
    for (files_json,) in rows:
        try:
            files = json.loads(files_json)
            for f in files:
                if f:
                    # Normalize to basename for counting
                    basename = os.path.basename(f)
                    file_counts[basename] += 1
        except:
            pass

    return file_counts.most_common(20)


def write_patterns(tool_patterns, success_patterns, failures, outcomes, hotspots):
    """Write extracted patterns to markdown file."""
    lines = [
        "# Learned Patterns",
        f"*Auto-generated by extract-patterns.py on {datetime.now().strftime('%Y-%m-%d %H:%M')}*",
        "",
        "## Effective Strategies",
        "",
    ]

    # Recent successful decisions/fixes
    seen_titles = set()
    for p in success_patterns[:10]:
        title = p["title"] or ""
        if title in seen_titles or len(title) < 10:
            continue
        seen_titles.add(title)
        lines.append(f"- [{p['type']}] {title}")

    lines.extend([
        "",
        "## Common Failure Modes",
        "",
    ])

    seen_errors = set()
    for f in failures[:8]:
        error = f["error"][:120]
        if error in seen_errors or len(error) < 15:
            continue
        seen_errors.add(error)
        lines.append(f"- {f['title']}: `{error}`")

    lines.extend([
        "",
        "## File Hotspots (most-modified files)",
        "",
    ])
    for fname, count in hotspots[:10]:
        lines.append(f"- `{fname}` ({count} modifications)")

    lines.extend([
        "",
        "## Recent Session Learnings",
        "",
    ])
    for o in outcomes[:5]:
        if o["learned"]:
            lines.append(f"- **{o['request']}**: {o['learned']}")

    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote patterns to {OUTPUT}")
    print(f"  {len(success_patterns)} success patterns")
    print(f"  {len(failures)} failure patterns")
    print(f"  {len(hotspots)} file hotspots")
    print(f"  {len(outcomes)} session outcomes")


def main():
    if not os.path.exists(DB_PATH):
        print(f"ERROR: Database not found at {DB_PATH}")
        return

    db = sqlite3.connect(DB_PATH, timeout=10)
    db.execute("PRAGMA journal_mode=WAL")

    tool_patterns, success_patterns = extract_tool_patterns(db)
    failures = extract_failure_patterns(db)
    outcomes = extract_session_outcomes(db)
    hotspots = extract_file_hotspots(db)

    db.close()

    write_patterns(tool_patterns, success_patterns, failures, outcomes, hotspots)


if __name__ == "__main__":
    main()
